language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=x86_64-apple-darwin
      os: osx
cache: cargo
before_cache: |
  chmod -R a+r $HOME/.cargo
  if [[ "$TRAVIS_RUST_VERSION" == stable && "$TARGET" == x86_64-unknown-linux-musl ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi
before_script:
  - rustup component add clippy
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo build --verbose --all
  - cargo test --verbose --all
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable && "$TARGET" == x86_64-unknown-linux-musl ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
